name: Bug report
description: Create a bug report to help us improve
labels: ['bug']

# Note: Do NOT use commas(,) in options with 'multiple: true', the issue processing workflow won't be able to label it
body:
  - type: markdown
    attributes:
      value: |
        ### Read Before Proceeding Further

        This form is for submitting a **bug report**.
        If you are just seeking help, or you would like to submit a feature request, go back and choose a more suitable option from the list.

        Also, search for your issue in the repo to be sure it doesn't exist already.

        To enter your issue, fill out the form correctly and according to the instructions. Try to be as clear as possible and provide as many details as possible, to help our team better understand the issue and to resolve it faster.
        Issues with an unclear description or lacking information will have a lower priority. They may even get closed without taking action.

        Thanks for your understanding. We truly appreciate your effort to fill out this form!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly and concisely explain the problem.
    validations:
      required: true
  - type: dropdown
    id: affected-version
    attributes:
      label: Affected version
      description: Mark the version(s) affected by this problem.
      multiple: true
      options:
        - v2.0.0
        - v2.1.0
        - v2.2.0
        - v2.3.0
        - v2.4.0
        - v2.5.0
        - Latest
    validations:
      required: true
  - type: input
    id: repro-url
    attributes:
      label: Reproduction URL
      description: |
        Fork a [Codepen](https://codepen.io/niketpathak/pen/WNMKzoJ) or a [jsFiddle](https://jsfiddle.net/niketpathak/n3f2cmq9/) and hit save then copy-paste the URL here.
        _You can provide a GitHub repo only as a last resort. Keep in mind that it will be prioritized less as it makes the reproduction process slower._
      placeholder: https://jsfiddle.net/niketpathak/n3f2cmq9/
    validations:
      required: true
  - type: textarea
    id: repro-description
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to the provided reproduction link
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: Mark the browsers in which you see the problem on. _If you select `Other`, please explain it in `Additional context` section._
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Opera
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant console log output.
        _This will be automatically formatted into code, so no need for backticks._
      render: Shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.